### PR TITLE
Fixed test in .can file

### PR DESCRIPTION
**Pull request by fgiaimo**

### CODE REVIEW

**Comment by olbender** [comment]
Thank you! Does this also include the most recent DBC support? I mean, if I compile and successfully test this on Rhino, is that a confirmation that we found the original error? I will test this during the day...

**Comment by fgiaimo** [comment]
Unfortunately that is unlikely to solve the problem, it's more of a overlook I did last time. All the other instances of the old messages are contained under the REMOVE.ME subtree, so I didn't bother changing them.
The bug itself still needs to be hunt down and fixed.

**Comment by olbender** [comment]
Ok, but should we perhaps then try to include the full fix in this PR to reduce overhead? Also we should soon move this module to opendlv.rhino, but I think we should do that when we know for certain that it works.

**Comment by chrberger** [comment]
I suggest that Federico and Ola check this status on Monday so that we can decide whether we rollback the dbc change in this master branch (and subsequently in OpenDLV) so that we have a working version again and move this change back to a branch to be fixed.

I would leave the decision about the strategy up to the two of you how to proceed.

**Review by olbender — APPROVED** [review]
@fgiaimo If this is compatible with v5 of the dbc, I suggest that we include it in the next version (togher with the rollback). @bjornborg Include this change in your pre-release test.

**Comment by fgiaimo** [comment]
@olbender the name changed in this PR is not compatible with v5, as this branch was meant to be used to work on v6

**Comment by olbender** [comment]
Ouch, so we should roll back then?

**Comment by fgiaimo** [comment]
For v5, yes

**Pull request merged**
