### PR TITLE
2017Q1.experiment.asta.jan.old dbc

### PR DESCRIPTION
**Pull request by bjornborg**
This will integrate the solution that was used on asta zero using the A double vehicle combination.
It will also revert the DBC file to the former one since the new one did not function properly.

### CODE REVIEW

**Comment by olbender** [comment]
@fgiaimo @chrberger I think the changes look good, but we need to commonly decide to revert the dbc changes. This will make it work again, but would we rather want to find the problem with the new dbc? To some extent this depends on @fgiaimo's availability. There will also soon be a new update to the dbc, perhaps already tomorrow. Should we perhaps then even drop the support for v6 and go directly to v7?

**Comment by fgiaimo** [comment]
It is ok for me to revert master to v5 while I work on v6 (just move the current master on a separate branch).
If a new version is indeed coming out tomorrow, then from next week I might as well drop v6 entirely and focus directly on the v7 integration; if it's not coming out for another few days then I'll just continue to iteratively integrate the changes introduced by v6 until I find out how we get the fault.

**Comment by chrberger** [comment]
Hi,

I would agree to revert to v5.

Please remember that we have subsequent changes in OpenDLV due to the renaming that took place there as well.

So, before we make the merge in OpenDLV.core to master, we need to have a branch in OpenDLV that would compile with OpenDLV.core/pre-release and merge both making two new releases so that they are in sync again.

Then, for v7, I suggest that we only allow the merge to master if the behavior has been verified in the separate branch on the truck.

What do you think?

**Review by olbender — APPROVED** [review]
Great. Merge this with pre-release and test it towards opendlv before we merge to master.

**Comment by bjornborg** [comment]
I will test it now.

**Comment by olbender** [comment]
Make sure to include @fgiaimo's PR in the test. 
https://github.com/chalmers-revere/opendlv.core/pull/86

**Comment by fgiaimo** [comment]
@chrberger sounds good for me. 
To sync opendlv should be easy, at a first analysis there are only 3 small commits that need to be reverted to roll back to v5 ("Renamed message"x3, on Dec 14th)

**Comment by olbender** [comment]
These are already rolled back in the experiment.asta.jan, so no change should be needed. But we need to test.

**Comment by bjornborg** [comment]
There are some broken dependencies in opendlv layer (included @fgiaimo's PR). But I will fixed them asap.

**Pull request merged**
