### PR TITLE
2016Q4.feature.beacons

### PR DESCRIPTION
**Pull request by chrberger**

### CODE REVIEW

**Review by bjornborg — APPROVED** [review]

**Comment by chrberger** [comment]
@bjornborg Is this tool tested on the BeagleBones so that we know that this component works?

**Comment by bjornborg** [comment]
I will check this tomorrow at the lab.

**Comment by bjornborg** [comment]
I just noticed there is no designed usecase for this. Should I construct one?

**Comment by chrberger** [comment]
Oh, that's right. Yes, we need a test-beacons use case.

**Comment by chrberger** [comment]
The specific challenge herewith is that the GPIO interface on Linux allows you to dynamically create filesystem entries for your GPIO pins. Thus, we cannot use Docker --device mapping but need to map the entire host's /dev to /from.host/dev inside the Docker container to modify the entries therein.

**Pull request closed without merging**
