### PR TITLE
2017Q2.feature.applanix

### PR DESCRIPTION
**Pull request by chrberger**
Refactoring proxy-applanix and more messages

### CODE REVIEW

**Comment by chrberger** [comment]
@olbender May I ask for your review?

**Comment by chrberger** [comment]
@olbender May I ask for your review?

**Comment by chrberger** [comment]
@bjornborg May I ask for your review and approval for the updated Applanix decoder?

**Review by bjornborg — APPROVED** [review]

**Comment by chrberger** [comment]
Thank you

**Pull request merged**
